import { generateConstantsFile } from '../createFile'

const myinvestimnts = [
  {
    symbol: 'KNRI11',
    side: 49,
    leavesAmount: 0,
    executedAmount: 29,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Fii kinea',
      quoteFactor: 1,
      unitPrice: 163.91,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 100,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/KNRI.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/KNRI.svg',
      typeMarket: 0,
      active: 'KNRI11',
      variation: 0.998,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 0,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'MXRF11',
    side: 49,
    leavesAmount: 0,
    executedAmount: 122,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Fii maxi ren',
      quoteFactor: 1,
      unitPrice: 11.12,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/MXRF.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/MXRF.svg',
      typeMarket: 0,
      active: 'MXRF11',
      variation: 0.271,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 0,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'MGFF11',
    side: 49,
    leavesAmount: 0,
    executedAmount: 11,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Fii mogno',
      quoteFactor: 1,
      unitPrice: 67.94,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/MGFF.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/MGFF.svg',
      typeMarket: 0,
      active: 'MGFF11',
      variation: 0.981,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 0,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'BBSE3',
    side: 49,
    leavesAmount: 0,
    executedAmount: 100,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'BB Seguridade',
      quoteFactor: 1,
      unitPrice: 31.62,
      standartLot: 100,
      stress: {
        value: 17,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 2,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/BBSE.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/BBSE.svg',
      typeMarket: 0,
      active: 'BBSE3',
      variation: -0.252,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'BBSE3F',
    side: 49,
    leavesAmount: 0,
    executedAmount: 5,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'BB Seguridade',
      quoteFactor: 1,
      unitPrice: 31.65,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/BBSE.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/BBSE.svg',
      typeMarket: 0,
      active: 'BBSE3F',
      variation: -0.158,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'MFII11',
    side: 49,
    leavesAmount: 0,
    executedAmount: 27,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Fii merito i',
      quoteFactor: 1,
      unitPrice: 93.97,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/MFII.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/MFII.svg',
      typeMarket: 0,
      active: 'MFII11',
      variation: -0.35,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 0,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'AMER3',
    side: 49,
    leavesAmount: 0,
    executedAmount: 100,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'AMERICANAS',
      quoteFactor: 1,
      unitPrice: 0.81,
      standartLot: 100,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/AMER.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/AMER.svg',
      typeMarket: 0,
      active: 'AMER3',
      variation: -5.814,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'TAEE11F',
    side: 49,
    leavesAmount: 0,
    executedAmount: 61,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Taesa',
      quoteFactor: 1,
      unitPrice: 35.2,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 0,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/TAEE.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/TAEE.svg',
      typeMarket: 0,
      active: 'TAEE11F',
      variation: 0.802,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'TASA4',
    side: 49,
    leavesAmount: 0,
    executedAmount: 200,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Taurus armas',
      quoteFactor: 1,
      unitPrice: 16.47,
      standartLot: 100,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 100,
        dayTradeValue: 100,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/TASA.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/TASA.svg',
      typeMarket: 0,
      active: 'TASA4',
      variation: -0.663,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'AESB3',
    side: 49,
    leavesAmount: 0,
    executedAmount: 100,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Aes brasil',
      quoteFactor: 1,
      unitPrice: 11.65,
      standartLot: 100,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 100,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/AESB.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/AESB.svg',
      typeMarket: 0,
      active: 'AESB3',
      variation: -0.257,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 1,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
  {
    symbol: 'BCFF11',
    side: 49,
    leavesAmount: 0,
    executedAmount: 61,
    priceType: 0,
    averagePriceExecuted: 0,
    status: 0,
    instrument: {
      description: 'Fii bc ffii',
      quoteFactor: 1,
      unitPrice: 72.03,
      standartLot: 1,
      stress: {
        value: 100,
        isPtax: false,
        composeNetEquity: false,
        dayTradeStrategyValue: 1,
        dayTradeValue: 100,
      },
      logoPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote/BCFF.svg',
      logoSquaredPath:
        'https://cdn.toroinvestimentos.com.br/corretora/images/quote-square/BCFF.svg',
      typeMarket: 0,
      active: 'BCFF11',
      variation: 0.306,
      rangeMinimumPriceIncrements: '0.01',
      brokerageFactor: 0,
      isPrioritized: false,
    },
    originType: null,
    originDescription: '',
    orderQuantity: 0,
    investmentType: 2,
    averagePrice: 0,
    ordersAmountInvested: 0,
  },
]
const groupActives = myinvestimnts.map(({ symbol, executedAmount }) => {
  return {
    symbol,
    executedAmount,
  }
})

export function startParseInvestiments() {
  generateConstantsFile(
    groupActives,
    'ParsedInvestiments',
    'src/investmentsParser',
  )
}
